extraction:
  cpp:
    prepare:
      packages:
        - qt5-default
        - qt5-qmake
        - qtbase5-dev
        - qtdeclarative5-dev
        - qtbase5-dev-tools
        - libqt5sql5-mysql
        - libqt5sql5-psql
        - libqt5sql5-odbc
        - libqt5sql5-sqlite
        - libqt5core5a
        - libqt5qml5
        - libqt5xml5
        - gcc
        - g++
        - make
    configure:
      command:
        - ./configure
        - touch Makefile
    index:
      build_command:
        - cd src
        - make -j2
