version: 2
jobs:
  bionic:
    docker:
      - image: buildpack-deps:bionic-curl
        environment:
          DEBIAN_FRONTEND: noninteractive
    working_directory: /workspace
    steps:
      - checkout
      - run: apt-get update -qq; apt install -y --no-install-recommends gcc g++ make cmake qtbase5-dev qt5-default qt5-qmake qttools5-dev-tools qtdeclarative5-dev qtdeclarative5-dev-tools libqt5sql5 libqt5sql5-sqlite libsqlite3-dev libmongoc-dev libbson-dev
      - run: qmake -v
      - run: ./configure --prefix=/usr/local
      - run: make -j4 -C src && make -C src install && make -j4 -C tools && make -C tools install
      - run: qmake tools/tmake/test/tmaketest.pro -o tools/tmake/test/Makefile && make -j4 -C tools/tmake/test
      - run: treefrog -v
      - persist_to_workspace:
          root: /
          paths:
            - workspace
            - usr/local
  ubuntu_shared_mongoc:
    docker:
      - image: buildpack-deps:focal-curl
        environment:
          DEBIAN_FRONTEND: noninteractive
    working_directory: /workspace
    steps:
      - checkout
      - run: apt-get update -qq; apt install -y --no-install-recommends gcc g++ clang make cmake qtbase5-dev qt5-default qt5-qmake qttools5-dev-tools qtdeclarative5-dev qtdeclarative5-dev-tools libqt5sql5 libqt5sql5-sqlite libsqlite3-dev libmongoc-dev libbson-dev
      - run: qmake -v
      - run: ./configure --prefix=/usr/local --enable-shared-mongoc --spec=linux-clang
      - run: make -j4 -C src && make -C src install && make -j4 -C tools && make -C tools install
      - run: treefrog -v
  test:
    docker:
      - image: buildpack-deps:bionic-curl
        environment:
          DEBIAN_FRONTEND: noninteractive
    working_directory: /workspace
    steps:
      - attach_workspace:
          at: /
      - run: apt-get update -qq; apt install -y --no-install-recommends gcc g++ make cmake qtbase5-dev qt5-default qt5-qmake qttools5-dev-tools qtdeclarative5-dev qtdeclarative5-dev-tools libqt5sql5 libqt5sql5-sqlite libsqlite3-dev libmongoc-dev libbson-dev sqlite3 jq
      - run: src/test/testall.sh
      - run: tools/tmake/test/tmaketest.sh
      - run: tools/test/releasetest/releasetest
workflows:
  version: 2
  build_test1:
    jobs:
      - bionic
      - test:
          requires:
            - bionic
      - ubuntu_shared_mongoc
