#!/usr/bin/env bash

tag_name="analyze_image_magick"
docker build . -t "$tag_name" 1>/dev/null && \
    # privileged is to change the ASLR \
    docker run -it --privileged --pid=host -v "$PWD/":"/project" "$tag_name"